$(function(){ 
	$('.lien_cache').hide(); 
	$('.lien_section').mouseenter(function(){ 
		$(this).children(':last').show(); 
	}); 
	$('.lien_section').mouseleave(function(){ 
		$(this).children(':last').hide(); 
	});
}); 
